# Generated by Django 4.2.1 on 2023-08-05 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('license_number', models.CharField(max_length=12, unique=True)),
                ('address', models.CharField(max_length=55)),
                ('zip', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license_status', models.CharField(max_length=55)),
                ('image', models.ImageField(null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_contractor', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('first_name', models.CharField(max_length=18)),
                ('last_name', models.CharField(max_length=18)),
                ('username', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=55, null=True)),
                ('zip', models.CharField(max_length=5, null=True)),
                ('company', models.CharField(choices=[('None', 'Not on the list')], default='None')),
                ('position', models.CharField(choices=[('Owner', 'Owner'), ('Administrator', 'Administrator'), ('Technician', 'Technician'), ('Other', 'Other')], default='Other')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('service_provided', models.CharField(max_length=32)),
                ('customer_info', models.TextField(max_length=200)),
                ('invoice_number', models.CharField(max_length=18)),
                ('invoice_photo', models.ImageField(default='', upload_to='invoices')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('body', models.TextField(max_length=800)),
                ('attachment', models.ImageField(null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_author', to='pages.member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_inquiry', to='pages.post')),
            ],
            options={
                'verbose_name_plural': 'inquiries',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=800)),
                ('attachment', models.ImageField(null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='pages.member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='pages.post')),
            ],
        ),
    ]
