# Generated by Django 4.2.1 on 2023-05-31 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=800)),
                ('attachment', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('license_number', models.CharField(db_index=True, max_length=12, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=55)),
                ('zip', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=18, unique=True)),
                ('first_name', models.CharField(max_length=18)),
                ('last_name', models.CharField(max_length=18)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=55)),
                ('zip', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('body', models.TextField(max_length=800)),
                ('post_id', models.CharField(max_length=10)),
                ('attachment', models.ImageField(upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'inquiries',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('service_provided', models.CharField(max_length=32)),
                ('customer_info', models.TextField(max_length=200)),
                ('invoice', models.CharField(max_length=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=18, unique=True)),
                ('first_name', models.CharField(max_length=18)),
                ('last_name', models.CharField(max_length=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='pages.company')),
            ],
        ),
    ]
