# Generated by Django 4.2.1 on 2023-06-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='company',
            field=models.CharField(choices=[('None', 'Not on the list'), ('Major', 'Major'), ('Invalid', 'Invalid')], default='None'),
        ),
        migrations.AlterField(
            model_name='post',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
