# Generated by Django 4.2.1 on 2023-06-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
