# Generated by Django 4.2.1 on 2023-06-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_comment_attachment_alter_company_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Administrator', 'Administrator'), ('Technician', 'Technician'), ('Other', 'Other')], default='Other'),
        ),
    ]
