# Generated by Django 4.2.1 on 2023-06-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_member_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='test',
            field=models.CharField(choices=[('major', 'major'), ('approved', 'approved')], default='test'),
        ),
    ]
