# Generated by Django 4.2.1 on 2023-06-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_member_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='test',
        ),
        migrations.AlterField(
            model_name='member',
            name='company',
            field=models.CharField(choices=[('None', 'Not on the list'), ('major', 'major'), ('approved', 'approved')], default='test'),
        ),
    ]
