version: "3.9" 

services:

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_container
    volumes:
      - ./backend:/app
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=base.settings
    expose:
      - 8000
    # ports:
    #   - "8000:8000"  
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx-config
      dockerfile: Dockerfile.nginx
    container_name: nginx_container
    ports:
      - "80:80" 
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./backend/pages/static:/static
      - ./backend/media:/media 
    depends_on:
      - django
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost/static/pages/login.css"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10

  db:
    image: postgres:15  
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  